/* examples/abortus/exempla.c -- guarded wrappers over three library-mode
 * units: custos (examples/custos/), arca (examples/arca/) and the test-only
 * probatio.exsc beside this file. Each wrapper is the pattern tutela.h shows:
 * a context struct, a thunk with no setjmp, and one call to
 * exs_tutela_curre. Every wrapper returns 0 or the trap's kind and writes its
 * result only on 0.
 *
 * Hand-written, not generated: README.md, "Why the wrappers are not
 * generated by exsc". exempla.h pins their signatures for the Rust host. */
#include <stdint.h>
#include "tutela.h"
#include "exempla.h"

/* The raw functions. The emitted units define them; custos.h and arca.h are
 * their C faces, but those two also say the trap hook must not return, which
 * is the sentence this example exists to qualify, so the prototypes are
 * repeated here rather than included. A drift from the definitions is a
 * compile error: proba_c.sh force-includes custos.h and arca.h into this
 * file's build as well. */
uint64_t exs_admitte(unsigned char *d, uint64_t n);
uint64_t exs_redundantia_sarcinae(unsigned char *d, uint64_t n);
uint64_t exs_magnitudo(unsigned char *h);
uint64_t exs_saltus(uint64_t m);
uint64_t exs_nomen_iudica(unsigned char *b, uint64_t n);
uint64_t exs_imple_et_cade(unsigned char *v, uint64_t n);
uint64_t exs_circuitus(uint64_t n);
uint64_t exs_profunda(uint64_t k, uint64_t n);

/* ---- custos --------------------------------------------------------------- */

struct ctx_admitte { unsigned char *d; uint64_t n; uint64_t r; };
static void opus_admitte(void *p)
{ struct ctx_admitte *c = p; c->r = exs_admitte(c->d, c->n); }
unsigned custos_admitte_tutum(unsigned char *d, uint64_t n, uint64_t *r)
{
  struct ctx_admitte c = { d, n, 0 };
  unsigned k = exs_tutela_curre(opus_admitte, &c);
  if (k == 0) *r = c.r;
  return k;
}

struct ctx_sarcina { unsigned char *d; uint64_t n; uint64_t r; };
static void opus_sarcina(void *p)
{ struct ctx_sarcina *c = p; c->r = exs_redundantia_sarcinae(c->d, c->n); }
unsigned custos_redundantia_sarcinae_tutum(unsigned char *d, uint64_t n, uint64_t *r)
{
  struct ctx_sarcina c = { d, n, 0 };
  unsigned k = exs_tutela_curre(opus_sarcina, &c);
  if (k == 0) *r = c.r;
  return k;
}

/* ---- arca ----------------------------------------------------------------- */

struct ctx_saltus { uint64_t m; uint64_t r; };
static void opus_saltus(void *p)
{ struct ctx_saltus *c = p; c->r = exs_saltus(c->m); }
unsigned arca_saltus_tutum(uint64_t m, uint64_t *r)
{
  struct ctx_saltus c = { m, 0 };
  unsigned k = exs_tutela_curre(opus_saltus, &c);
  if (k == 0) *r = c.r;
  return k;
}

/* What a host loop does with a header it has not yet judged: the size, then
 * the bytes to skip. On a malformed size field magnitudo returns its
 * sentinel 0xffffffffffffffff and saltus's `m + 511` overflows -- a trap one
 * missing verdict check away from any input. */
struct ctx_saltus_capitis { unsigned char *h; uint64_t r; };
static void opus_saltus_capitis(void *p)
{ struct ctx_saltus_capitis *c = p; c->r = exs_saltus(exs_magnitudo(c->h)); }
unsigned arca_saltus_capitis_tutum(unsigned char *h, uint64_t *r)
{
  struct ctx_saltus_capitis c = { h, 0 };
  unsigned k = exs_tutela_curre(opus_saltus_capitis, &c);
  if (k == 0) *r = c.r;
  return k;
}

struct ctx_nomen { unsigned char *b; uint64_t n; uint64_t r; };
static void opus_nomen(void *p)
{ struct ctx_nomen *c = p; c->r = exs_nomen_iudica(c->b, c->n); }
unsigned arca_nomen_iudica_tutum(unsigned char *b, uint64_t n, uint64_t *r)
{
  struct ctx_nomen c = { b, n, 0 };
  unsigned k = exs_tutela_curre(opus_nomen, &c);
  if (k == 0) *r = c.r;
  return k;
}

/* ---- probatio.exsc (test-only) ------------------------------------------- */

struct ctx_imple { unsigned char *v; uint64_t n; uint64_t r; };
static void opus_imple(void *p)
{ struct ctx_imple *c = p; c->r = exs_imple_et_cade(c->v, c->n); }
unsigned probatio_imple_tutum(unsigned char *v, uint64_t n, uint64_t *r)
{
  struct ctx_imple c = { v, n, 0 };
  unsigned k = exs_tutela_curre(opus_imple, &c);
  if (k == 0) *r = c.r;
  return k;
}

struct ctx_circuitus { uint64_t n; uint64_t r; };
static void opus_circuitus(void *p)
{ struct ctx_circuitus *c = p; c->r = exs_circuitus(c->n); }
unsigned probatio_circuitus_tutum(uint64_t n, uint64_t *r)
{
  struct ctx_circuitus c = { n, 0 };
  unsigned k = exs_tutela_curre(opus_circuitus, &c);
  if (k == 0) *r = c.r;
  return k;
}

struct ctx_profunda { uint64_t k; uint64_t n; uint64_t r; };
static void opus_profunda(void *p)
{ struct ctx_profunda *c = p; c->r = exs_profunda(c->k, c->n); }
unsigned probatio_profunda_tutum(uint64_t k, uint64_t n, uint64_t *r)
{
  struct ctx_profunda c = { k, n, 0 };
  unsigned g = exs_tutela_curre(opus_profunda, &c);
  if (g == 0) *r = c.r;
  return g;
}
